[package]
name = "bookie-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
crossterm = "0.29"        # terminal + raw mode
fern = "0.7"              # simple file logging
log = "0.4"
serde_json = "1.0"
serde = { version = "1.0.228", features = ["derive"] }