[package]
name = "bookie-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
color-eyre = "0.6.5"
crossterm = "0.29"        # terminal + raw mode
fern = "0.7"              # simple file logging
log = "0.4"
ratatui = "0.30.0-beta.0" # tui widgets & layout (alias of tui-rs fork)
